spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #use_sql_comments: 'true'
        #format_sql: 'true'
        show_sql: 'true'
        ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/jwt_db?useSSL=false

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql:
#              BasicBinder: DEBUG
#          nodeValue: DEBUG
#        SQL: DEBUG
app:
  jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  #600,000 Milliseconds = 10 minutes - https://www.flightpedia.org/convert/10-minute-to-millisecond.html
  jwtExpirationMs: '600000'
