# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title


title: Application security blogs
email: badki_shital@yahoo.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blogs" # the subpath of your site, e.g. /blog
url: "https://sbadki.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  sbdki

# Build settings
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
JB :
  version : 0.3.0
  BASE_PATH : https://sbadki.github.io/applicationsecurity

  archive_path: nil
  categories_path : nil
  tags_path : nil
  atom_path : nil
  rss_path : nil

  comments:
    provider: false

  analytics :
    provider : false

  sharing :
    provider : false
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
