server:
 port: 9080

spring:
  application:
    name: springboot-oauth2-security

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}

          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

logging:
  level:
    org:
      springframework:
        security: TRACE